export const BACKEND = 'https://api.mangadex.org'
export const UPLOADS = 'https://uploads.mangadex.org'
export const FRONTEND = 'https://mangadex.org'
export const CDN = 'https://api.mangadex.org/at-home/server'
export const AUTH_REALM = 'https://auth.mangadex.dev/realms/mangadex'
export const OAUTH_CLIENT_ID = ''
export const COMMENTS = 'https://forums.mangadex.org/threads'
